/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Monitor;

import java.awt.Color;
import java.awt.GraphicsConfiguration;
import java.awt.MenuItem;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import java.io.IOException;
import java.io.FileReader;
import java.io.BufferedReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author garcil5
 */
public class Sibas extends javax.swing.JFrame {
    int r = 0;
    int maxNumberOfLines = 27;
    String phrase;
    /**
     * Creates new form Sibas
     */
    public Sibas() {
        initComponents();
        String fn = "init";
        initi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsBox = new javax.swing.JTextArea();
        editBox = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        UIManager.put("Menu.selectionBackground",new Color(192,192,192));
        UIManager.put("MenuItem.selectionBackground",new Color(192,192,192));
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        UIManager.put("Menu.selectionBackground",new Color(192,192,192));
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenuItem64 = new javax.swing.JMenuItem();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenuItem68 = new javax.swing.JMenuItem();
        jMenuItem69 = new javax.swing.JMenuItem();
        jMenuItem70 = new javax.swing.JMenuItem();
        jMenuItem71 = new javax.swing.JMenuItem();
        jMenuItem72 = new javax.swing.JMenuItem();
        jMenuItem73 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem74 = new javax.swing.JMenuItem();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenuItem76 = new javax.swing.JMenuItem();
        jMenuItem77 = new javax.swing.JMenuItem();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenuItem79 = new javax.swing.JMenuItem();
        jMenuItem80 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem81 = new javax.swing.JMenuItem();
        jMenuItem82 = new javax.swing.JMenuItem();
        jMenuItem83 = new javax.swing.JMenuItem();
        jMenuItem84 = new javax.swing.JMenuItem();
        jMenuItem85 = new javax.swing.JMenuItem();
        jMenuItem86 = new javax.swing.JMenuItem();
        jMenuItem87 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem88 = new javax.swing.JMenuItem();
        jMenuItem89 = new javax.swing.JMenuItem();
        jMenuItem90 = new javax.swing.JMenuItem();
        jMenuItem91 = new javax.swing.JMenuItem();
        jMenuItem92 = new javax.swing.JMenuItem();
        jMenuItem93 = new javax.swing.JMenuItem();
        jMenuItem94 = new javax.swing.JMenuItem();
        jMenuItem95 = new javax.swing.JMenuItem();
        jMenuItem96 = new javax.swing.JMenuItem();
        jMenuItem97 = new javax.swing.JMenuItem();
        jMenuItem98 = new javax.swing.JMenuItem();
        jMenuItem99 = new javax.swing.JMenuItem();
        jMenuItem100 = new javax.swing.JMenuItem();
        jMenuItem101 = new javax.swing.JMenuItem();
        jMenuItem102 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem103 = new javax.swing.JMenuItem();
        jMenuItem104 = new javax.swing.JMenuItem();
        jMenuItem105 = new javax.swing.JMenuItem();
        jMenuItem106 = new javax.swing.JMenuItem();
        jMenuItem107 = new javax.swing.JMenuItem();
        jMenuItem108 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem109 = new javax.swing.JMenuItem();
        jMenuItem110 = new javax.swing.JMenuItem();
        jMenuItem111 = new javax.swing.JMenuItem();
        jMenuItem112 = new javax.swing.JMenuItem();
        jMenuItem113 = new javax.swing.JMenuItem();
        jMenuItem114 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem115 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setVerifyInputWhenFocusTarget(false);

        resultsBox.setColumns(20);
        resultsBox.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        resultsBox.setLineWrap(true);
        resultsBox.setRows(5);
        resultsBox.setAutoscrolls(false);
        resultsBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(resultsBox);
        resultsBox.getAccessibleContext().setAccessibleDescription("");
        resultsBox.getAccessibleContext().setAccessibleParent(resultsBox);

        editBox.setEditable(false);
        editBox.setBackground(new java.awt.Color(255, 255, 0));
        editBox.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 15)); // NOI18N
        editBox.setText(" Edit:");
        editBox.setToolTipText("");
        editBox.setBorder(null);
        editBox.setSelectionColor(new java.awt.Color(255, 255, 0));
        editBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editBox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar2.setBackground(new java.awt.Color(224, 224, 224));
        jMenuBar2.setAlignmentY(0.5F);

        jMenu1.setBorder(null);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Monitor/sibas_icon.png"))); // NOI18N
        jMenu1.setAutoscrolls(true);
        jMenu1.setFocusable(false);
        jMenu1.setRequestFocusEnabled(false);
        jMenu1.setRolloverEnabled(false);
        jMenu1.setVerifyInputWhenFocusTarget(false);
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Window");

        jMenuItem1.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem1.setText("Work Open");
        jMenuItem1.setBorder(null);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem2.setText("Lines Open");
        jMenuItem2.setBorder(null);
        jMenu3.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem3.setText("Bars Open");
        jMenuItem3.setBorder(null);
        jMenu3.add(jMenuItem3);

        jMenuItem4.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem4.setText("Tile");
        jMenuItem4.setBorder(null);
        jMenu3.add(jMenuItem4);

        jMenuItem5.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem5.setText("Cascade");
        jMenuItem5.setBorder(null);
        jMenu3.add(jMenuItem5);

        jMenuItem6.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem6.setText("Set");
        jMenuItem6.setBorder(null);
        jMenu3.add(jMenuItem6);

        jMenuItem7.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem7.setText("Close");
        jMenuItem7.setBorder(null);
        jMenu3.add(jMenuItem7);

        jMenuItem8.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem8.setText("Close All");
        jMenuItem8.setBorder(null);
        jMenu3.add(jMenuItem8);

        jMenuItem9.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem9.setText("Exit");
        jMenuItem9.setBorder(null);
        jMenu3.add(jMenuItem9);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Set");

        jMenuItem10.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem10.setText("Port");
        jMenuItem10.setBorder(null);
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem11.setText("Baudrate");
        jMenuItem11.setBorder(null);
        jMenu4.add(jMenuItem11);

        jMenuItem12.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem12.setText("FTP");
        jMenuItem12.setBorder(null);
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem13.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem13.setText("String");
        jMenuItem13.setBorder(null);
        jMenu4.add(jMenuItem13);

        jMenuItem14.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem14.setText("Make");
        jMenuItem14.setBorder(null);
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuItem15.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem15.setText("Execute");
        jMenuItem15.setBorder(null);
        jMenu4.add(jMenuItem15);

        jMenuItem16.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem16.setText("Record");
        jMenuItem16.setBorder(null);
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuItem17.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem17.setText("Level");
        jMenuItem17.setBorder(null);
        jMenu4.add(jMenuItem17);

        jMenuItem18.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem18.setText("DIN Bus");
        jMenuItem18.setBorder(null);
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem18);

        jMenuItem19.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem19.setText("TCN");
        jMenuItem19.setBorder(null);
        jMenu4.add(jMenuItem19);

        jMenuItem20.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem20.setText("ACC_Cust.");
        jMenuItem20.setBorder(null);
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem20);

        jMenuItem21.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem21.setText("ACC_Proj.");
        jMenuItem21.setBorder(null);
        jMenu4.add(jMenuItem21);

        jMenuItem22.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem22.setText("Timeout");
        jMenuItem22.setBorder(null);
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem22);

        jMenuItem23.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem23.setText("Wait");
        jMenuItem23.setBorder(null);
        jMenu4.add(jMenuItem23);

        jMenuItem24.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem24.setText("Color");
        jMenuItem24.setBorder(null);
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem24);

        jMenuItem25.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem25.setText("INFO");
        jMenuItem25.setBorder(null);
        jMenu4.add(jMenuItem25);

        jMenuItem26.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem26.setText("COMment");
        jMenuItem26.setBorder(null);
        jMenu4.add(jMenuItem26);

        jMenuItem27.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem27.setText("CHAR Set");
        jMenuItem27.setBorder(null);
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem27);

        jMenuItem28.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem28.setText("Options");
        jMenuItem28.setBorder(null);
        jMenu4.add(jMenuItem28);

        jMenuItem29.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem29.setText("Quit");
        jMenuItem29.setBorder(null);
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem29);

        jMenuBar2.add(jMenu4);

        jMenu2.setText("Applic.");

        jMenuItem30.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem30.setText("Func. Package");
        jMenuItem30.setBorder(null);
        jMenu2.add(jMenuItem30);

        jMenuItem31.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem31.setText("Connector");
        jMenuItem31.setBorder(null);
        jMenu2.add(jMenuItem31);

        jMenuItem32.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem32.setText("View");
        jMenuItem32.setBorder(null);
        jMenu2.add(jMenuItem32);

        jMenuItem33.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem33.setText("Signal");
        jMenuItem33.setBorder(null);
        jMenu2.add(jMenuItem33);

        jMenuItem34.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem34.setText("Observer");
        jMenuItem34.setBorder(null);
        jMenu2.add(jMenuItem34);

        jMenuItem35.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem35.setText("Buffer");
        jMenuItem35.setBorder(null);
        jMenu2.add(jMenuItem35);

        jMenuItem36.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem36.setText("Persistent");
        jMenuItem36.setBorder(null);
        jMenu2.add(jMenuItem36);

        jMenuItem37.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem37.setText("Ignore");
        jMenuItem37.setBorder(null);
        jMenu2.add(jMenuItem37);

        jMenuItem38.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem38.setText("Report");
        jMenuItem38.setBorder(null);
        jMenu2.add(jMenuItem38);

        jMenuItem39.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem39.setText("Legitimation");
        jMenuItem39.setBorder(null);
        jMenu2.add(jMenuItem39);

        jMenuItem40.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem40.setText("Utilization");
        jMenuItem40.setBorder(null);
        jMenu2.add(jMenuItem40);

        jMenuItem41.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem41.setText("Menu");
        jMenuItem41.setBorder(null);
        jMenu2.add(jMenuItem41);

        jMenuItem42.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem42.setText("Traco");
        jMenuItem42.setBorder(null);
        jMenu2.add(jMenuItem42);

        jMenuItem43.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem43.setText("Environment");
        jMenuItem43.setBorder(null);
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem43);

        jMenuItem44.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem44.setText("Quick-Mode");
        jMenuItem44.setBorder(null);
        jMenu2.add(jMenuItem44);

        jMenuBar2.add(jMenu2);

        jMenu5.setBackground(new java.awt.Color(224, 224, 224));
        jMenu5.setText("Memory");

        jMenuItem45.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem45.setText("Display");
        jMenuItem45.setBorder(null);
        jMenu5.add(jMenuItem45);

        jMenuItem46.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem46.setText("Set");
        jMenuItem46.setBorder(null);
        jMenu5.add(jMenuItem46);

        jMenuItem47.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem47.setText("Fill");
        jMenuItem47.setBorder(null);
        jMenuItem47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem47ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem47);

        jMenuItem48.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem48.setText("Move");
        jMenuItem48.setBorder(null);
        jMenu5.add(jMenuItem48);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Hardw.");

        jMenuItem49.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem49.setText("Flash");
        jMenuItem49.setBorder(null);
        jMenu6.add(jMenuItem49);

        jMenuItem50.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem50.setText("Clock");
        jMenuItem50.setBorder(null);
        jMenu6.add(jMenuItem50);

        jMenuItem51.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem51.setText("Timer");
        jMenuItem51.setBorder(null);
        jMenu6.add(jMenuItem51);

        jMenuItem52.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem52.setText("DSP");
        jMenuItem52.setBorder(null);
        jMenu6.add(jMenuItem52);

        jMenuItem53.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem53.setText("RS485/232");
        jMenuItem53.setBorder(null);
        jMenu6.add(jMenuItem53);

        jMenuItem54.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem54.setText("BCD");
        jMenuItem54.setBorder(null);
        jMenu6.add(jMenuItem54);

        jMenuItem55.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem55.setText("RESET");
        jMenuItem55.setBorder(null);
        jMenu6.add(jMenuItem55);

        jMenuItem56.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem56.setText("RAM-TEST");
        jMenuItem56.setBorder(null);
        jMenu6.add(jMenuItem56);

        jMenuItem57.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem57.setText("Report");
        jMenuItem57.setBorder(null);
        jMenu6.add(jMenuItem57);

        jMenuItem58.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem58.setText("Legitimation");
        jMenuItem58.setBorder(null);
        jMenu6.add(jMenuItem58);

        jMenuItem59.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem59.setText("Utilization");
        jMenuItem59.setBorder(null);
        jMenu6.add(jMenuItem59);

        jMenuItem60.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem60.setText("Sys. Flash");
        jMenuItem60.setBorder(null);
        jMenu6.add(jMenuItem60);

        jMenuItem61.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem61.setText("COMM-Version");
        jMenuItem61.setBorder(null);
        jMenu6.add(jMenuItem61);

        jMenuItem62.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem62.setText("BOOT DSP");
        jMenuItem62.setBorder(null);
        jMenu6.add(jMenuItem62);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Debug");

        jMenuItem63.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem63.setText("Next");
        jMenuItem63.setBorder(null);
        jMenu7.add(jMenuItem63);

        jMenuItem64.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem64.setText("Go");
        jMenuItem64.setBorder(null);
        jMenu7.add(jMenuItem64);

        jMenuItem65.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem65.setText("Breakp.");
        jMenuItem65.setBorder(null);
        jMenu7.add(jMenuItem65);

        jMenuItem66.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem66.setText("Register");
        jMenuItem66.setBorder(null);
        jMenu7.add(jMenuItem66);

        jMenuItem67.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem67.setText("Disass.");
        jMenuItem67.setBorder(null);
        jMenu7.add(jMenuItem67);

        jMenuItem68.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem68.setText("Application");
        jMenuItem68.setBorder(null);
        jMenu7.add(jMenuItem68);

        jMenuItem69.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem69.setText("Exception");
        jMenuItem69.setBorder(null);
        jMenu7.add(jMenuItem69);

        jMenuItem70.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem70.setText("Stack Info");
        jMenuItem70.setBorder(null);
        jMenu7.add(jMenuItem70);

        jMenuItem71.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem71.setText("Time Slices");
        jMenuItem71.setBorder(null);
        jMenu7.add(jMenuItem71);

        jMenuItem72.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem72.setText("Checksum");
        jMenuItem72.setBorder(null);
        jMenu7.add(jMenuItem72);

        jMenuItem73.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem73.setText("TRaco");
        jMenuItem73.setBorder(null);
        jMenu7.add(jMenuItem73);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Graphic");

        jMenuItem74.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem74.setText("Load");
        jMenuItem74.setBorder(null);
        jMenu8.add(jMenuItem74);

        jMenuItem75.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem75.setText("Position");
        jMenuItem75.setBorder(null);
        jMenu8.add(jMenuItem75);

        jMenuItem76.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem76.setText("Time/Div");
        jMenuItem76.setBorder(null);
        jMenu8.add(jMenuItem76);

        jMenuItem77.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem77.setText("Unit/Div");
        jMenuItem77.setBorder(null);
        jMenu8.add(jMenuItem77);

        jMenuItem78.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem78.setText("Display");
        jMenuItem78.setBorder(null);
        jMenu8.add(jMenuItem78);

        jMenuItem79.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem79.setText("Color");
        jMenuItem79.setBorder(null);
        jMenu8.add(jMenuItem79);

        jMenuItem80.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem80.setText("Format");
        jMenuItem80.setBorder(null);
        jMenu8.add(jMenuItem80);

        jMenuBar2.add(jMenu8);

        jMenu9.setText("TRACO");

        jMenuItem81.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem81.setText("ZR-Traco Set");
        jMenuItem81.setBorder(null);
        jMenu9.add(jMenuItem81);

        jMenuItem82.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem82.setText("ZR-Traco Out");
        jMenuItem82.setBorder(null);
        jMenuItem82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem82ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem82);

        jMenuItem83.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem83.setText("CROWD SIP");
        jMenuItem83.setBorder(null);
        jMenuItem83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem83ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem83);

        jMenuItem84.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem84.setText("HOIST SIP");
        jMenuItem84.setBorder(null);
        jMenu9.add(jMenuItem84);

        jMenuItem85.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem85.setText("SWING SIP");
        jMenuItem85.setBorder(null);
        jMenuItem85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem85ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem85);

        jMenuItem86.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem86.setText("AFE12 SIP");
        jMenuItem86.setBorder(null);
        jMenu9.add(jMenuItem86);

        jMenuItem87.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem87.setText("AFE34 SIP");
        jMenuItem87.setBorder(null);
        jMenu9.add(jMenuItem87);

        jMenuBar2.add(jMenu9);

        jMenu10.setText("Events");

        jMenuItem88.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem88.setText("STatistics");
        jMenuItem88.setBorder(null);
        jMenu10.add(jMenuItem88);

        jMenuItem89.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem89.setText("History");
        jMenuItem89.setBorder(null);
        jMenuItem89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem89ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem89);

        jMenuItem90.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem90.setText("LEL:Last EvL");
        jMenuItem90.setBorder(null);
        jMenu10.add(jMenuItem90);

        jMenuItem91.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem91.setText("LEL:Last EvS");
        jMenuItem91.setBorder(null);
        jMenu10.add(jMenuItem91);

        jMenuItem92.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem92.setText("DLL:DC,LastL");
        jMenuItem92.setBorder(null);
        jMenu10.add(jMenuItem92);

        jMenuItem93.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem93.setText("DLL:DC,LastS");
        jMenuItem93.setBorder(null);
        jMenu10.add(jMenuItem93);

        jMenuItem94.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem94.setText("DAL:DC ALL L");
        jMenuItem94.setBorder(null);
        jMenuItem94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem94ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem94);

        jMenuItem95.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem95.setText("DAL:DC ALL S");
        jMenuItem95.setBorder(null);
        jMenu10.add(jMenuItem95);

        jMenuItem96.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem96.setText("ML:Memory L");
        jMenuItem96.setBorder(null);
        jMenu10.add(jMenuItem96);

        jMenuItem97.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem97.setText("ML:Memory S");
        jMenuItem97.setBorder(null);
        jMenu10.add(jMenuItem97);

        jMenuItem98.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem98.setText("CN: ClearNorm");
        jMenuItem98.setBorder(null);
        jMenu10.add(jMenuItem98);

        jMenuItem99.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem99.setText("CA:Clear All");
        jMenuItem99.setBorder(null);
        jMenu10.add(jMenuItem99);

        jMenuItem100.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem100.setText("Snapshot");
        jMenuItem100.setBorder(null);
        jMenu10.add(jMenuItem100);

        jMenuItem101.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem101.setText("DS:Diag-Strc");
        jMenuItem101.setBorder(null);
        jMenu10.add(jMenuItem101);

        jMenuItem102.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem102.setText("Environment");
        jMenuItem102.setBorder(null);
        jMenu10.add(jMenuItem102);

        jMenuBar2.add(jMenu10);

        jMenu11.setText("Field");

        jMenuItem103.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem103.setText("Kundenstat");
        jMenuItem103.setBorder(null);
        jMenu11.add(jMenuItem103);

        jMenuItem104.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem104.setText("OFFline-PP");
        jMenuItem104.setBorder(null);
        jMenu11.add(jMenuItem104);

        jMenuItem105.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem105.setText("ONline-PP");
        jMenuItem105.setBorder(null);
        jMenu11.add(jMenuItem105);

        jMenuItem106.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem106.setText("EA:EingASGNr");
        jMenuItem106.setBorder(null);
        jMenu11.add(jMenuItem106);

        jMenuItem107.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem107.setText("EF:EingFZ-Nr");
        jMenuItem107.setBorder(null);
        jMenu11.add(jMenuItem107);

        jMenuItem108.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem108.setText("IP Address");
        jMenuItem108.setBorder(null);
        jMenu11.add(jMenuItem108);

        jMenuBar2.add(jMenu11);

        jMenu12.setText("Typetest");

        jMenuItem109.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem109.setText("Fire AFE12");
        jMenuItem109.setBorder(null);
        jMenu12.add(jMenuItem109);

        jMenuItem110.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem110.setText("Fire AFE34");
        jMenuItem110.setBorder(null);
        jMenu12.add(jMenuItem110);

        jMenuItem111.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem111.setText("Fire Crowd");
        jMenuItem111.setBorder(null);
        jMenu12.add(jMenuItem111);

        jMenuItem112.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem112.setText("Fire Swing");
        jMenuItem112.setBorder(null);
        jMenu12.add(jMenuItem112);

        jMenuItem113.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem113.setText("Fire Hoist");
        jMenuItem113.setBorder(null);
        jMenu12.add(jMenuItem113);

        jMenuItem114.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem114.setText("Typtest Mode");
        jMenuItem114.setBorder(null);
        jMenu12.add(jMenuItem114);

        jMenuBar2.add(jMenu12);

        jMenu13.setText("?");

        jMenuItem115.setBackground(new java.awt.Color(224, 224, 224));
        jMenuItem115.setText("Monitor / OS");
        jMenuItem115.setBorder(null);
        jMenu13.add(jMenuItem115);

        jMenuBar2.add(jMenu13);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        setPort();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        setMake();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem47ActionPerformed

    private void jMenuItem82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem82ActionPerformed

    private void jMenuItem83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem83ActionPerformed

    private void jMenuItem85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem85ActionPerformed

    private void jMenuItem89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem89ActionPerformed

    private void jMenuItem94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem94ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem94ActionPerformed

    private void editBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBoxActionPerformed


    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sibas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sibas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sibas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sibas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.put("Menu.selectionForeground", Color.red);
        /* Create and display the form */
         javax.swing.SwingUtilities.invokeLater(new Runnable() {       
            public void run() {
                new Sibas().setVisible(true);
                
            }
        });
    }

    public void initi () {
        String file_name;
        file_name =  "C:\\SIBAS32\\Simulator\\initFile.txt";
        try{
            ReadFile file = new ReadFile( file_name );

            String[ ] aryLines = file.OpenFile( );

            int i;
            for ( i=0; i < aryLines.length; i++ ) {
                updateResultsBox(aryLines[i]);
            }
            updateResultsBox("last");
        }
        catch (IOException e) {
            System.out.println(e.getMessage());
        }
}
    public void setPort () {
        updateResultsBox("first");
        r++;
        updateResultsBox(Integer.toString(r));
        updateResultsBox(Integer.toString(r));                
        updateResultsBox(Integer.toString(r));
        updateResultsBox("last");
    }
    
    public void setMake() {
        editEditBox("  Set  Make" + " ");
    }
    
    public void editEditBox (String expression) {
        int numberOfChar;
        phrase = editBox.getText();
        phrase = phrase + expression;
        numberOfChar = phrase.length();
        
        editBox.setText(phrase);
        editBox.setSize(numberOfChar * 9, 20);
    }
    
    public void runAction (String selectedAction) {
        
    }   
    
    public void updateResultsBox(String stuffToWrite) {

        if (stuffToWrite == "last") {
            
            int lineCount2 = resultsBox.getLineCount();
            
            if (lineCount2 >= maxNumberOfLines) {

                String[] habenero = resultsBox.getText().split("\n");
                resultsBox.setText(habenero[2] + "\n");

                for (int i=3; i < lineCount2 -1 ; i++) {
                    resultsBox.append(habenero[i] + "\n");
                }
                
                resultsBox.append("\n\n >");
                
            } else {
                resultsBox.append("\n\n >");
            }
            
        } else if (stuffToWrite == "first") {
            
            int numberOfLines = resultsBox.getLineCount();
            
            if (numberOfLines < maxNumberOfLines){
                
                String[] habenero = resultsBox.getText().split("\n");
                resultsBox.setText(habenero[0] + "\n");

                for (int i=1; i < (numberOfLines - 1 ); i++){
                    resultsBox.append(habenero[i] + "\n");
                }
            }
        } else {
            
            if (resultsBox.getLineCount() < maxNumberOfLines) {
            
                resultsBox.append(stuffToWrite + "\n");
            
            } else {
            
                int lineCount = resultsBox.getLineCount();
                String[] habenero = resultsBox.getText().split("\n");
                resultsBox.setText(habenero[1] + "\n");

                for (int i=2; i < lineCount - 1; i++) {
                    resultsBox.append(habenero[i] + "\n");
                }

                resultsBox.append(stuffToWrite + "\n");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField editBox;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem100;
    private javax.swing.JMenuItem jMenuItem101;
    private javax.swing.JMenuItem jMenuItem102;
    private javax.swing.JMenuItem jMenuItem103;
    private javax.swing.JMenuItem jMenuItem104;
    private javax.swing.JMenuItem jMenuItem105;
    private javax.swing.JMenuItem jMenuItem106;
    private javax.swing.JMenuItem jMenuItem107;
    private javax.swing.JMenuItem jMenuItem108;
    private javax.swing.JMenuItem jMenuItem109;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem110;
    private javax.swing.JMenuItem jMenuItem111;
    private javax.swing.JMenuItem jMenuItem112;
    private javax.swing.JMenuItem jMenuItem113;
    private javax.swing.JMenuItem jMenuItem114;
    private javax.swing.JMenuItem jMenuItem115;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem68;
    private javax.swing.JMenuItem jMenuItem69;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JMenuItem jMenuItem81;
    private javax.swing.JMenuItem jMenuItem82;
    private javax.swing.JMenuItem jMenuItem83;
    private javax.swing.JMenuItem jMenuItem84;
    private javax.swing.JMenuItem jMenuItem85;
    private javax.swing.JMenuItem jMenuItem86;
    private javax.swing.JMenuItem jMenuItem87;
    private javax.swing.JMenuItem jMenuItem88;
    private javax.swing.JMenuItem jMenuItem89;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem90;
    private javax.swing.JMenuItem jMenuItem91;
    private javax.swing.JMenuItem jMenuItem92;
    private javax.swing.JMenuItem jMenuItem93;
    private javax.swing.JMenuItem jMenuItem94;
    private javax.swing.JMenuItem jMenuItem95;
    private javax.swing.JMenuItem jMenuItem96;
    private javax.swing.JMenuItem jMenuItem97;
    private javax.swing.JMenuItem jMenuItem98;
    private javax.swing.JMenuItem jMenuItem99;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultsBox;
    // End of variables declaration//GEN-END:variables
}
